### ISSUE TITLE
transformar isto num "microsite", similar com o que a ANSOL fez com o "à distância"

### ISSUE THREAD

**Issue by marado** [marado/RNID#71]

**Comment by gsilvapt** [comment]
Jekyll tem uma feature altamente para isto: https://jekyllrb.com/docs/datafiles/ Utilizando os yamlo que tens, certamente que conseguias gerar secções inteiras com os ficheiros.

**Comment by hugopeixoto** [comment]
Comecei a olhar para isto.

Acho que o primeiro passo, antes de criar o site, vai passar por estruturar os dados dos incumprimentos para conseguirmos gerar tanto um readme como um site.

O ano passado [trabalhei um bocado nisto](https://github.com/hugopeixoto/RNID/tree/create-framework/scripts), mas não fiquei super contente com o que fiz, principalmente por estar limitado a bash scripts. O que decidi fazer desta vez foi passar os dados para ficheiros yaml como este:

```yaml
---
website: https://www.parlamento.pt
incumprimentos:
- description: Vídeos disponibilizados em WMV
  url: "/ActividadeParlamentar/Paginas/DetalheAudiencia.aspx?BID=99371"
  last_check: 2021-09-17
  auto:
    checker: diff_selector
    args:
      selector: "#ctl00_ctl50_g_1d0614cc_f7c9_4544_a067_a6d1e32c35ae_ctl00_pnlLinksAssociados"
      result: 4dd837114838be025fd983167f9dea07c9dea00b27a6071d2275beffe49007c6
```

Depois tenho um ruby script (ainda em construção) que pega nestes yaml e corre os checks lá descritos. Em conjunto com um script que gere o readme actual, isto será suficiente para reproduzir a funcionalidade actual.

- desvantagem: precisar de ruby e uma ou duas gems para correr os checks (em vez de ser só para correr o Jekyll)
- vantagem: garantir que o readme não dessincroniza dos scripts de verificação (neste momento há meia dúzia de inconsistências)
- vantagem: mais fácil adicionar scripts de verificação
- vantagem: poder usar css selectors num html parser um bocado mais robusto que os os `hx*`, que dão alguns problemas
